GAME_NAME = "Oasis of the Lost Adventure"
GAME_ICON = "./images/icon.png",
GAME_BANNER = "./images/banner.png"
GAME_COVER_PHOTO = "./images/cover_photo.png"
GAME_MAP_PATH = "./images/maps/oasis_map_{}.png"
GAME_ITEM_IMAGE_PATH = "./images/items/{}.png"
GAME_ENEMY_IMAGE_PATH = "./images/enemy/{}.png"
GAME_LOCATION_IMAGE_PATH = "./images/locations/{}.png"
PLAYER_ICON_IMAGE_PATH = "./images/player_icon.png"
NEW_GAME_DATA_PATH = "./data/new_game_layout.gamedata"
GAME_WALL_DATA_PATH = "./data/boundary.gamedata"
GAME_REQUIRED_ITEM_PATH = "./data/map_trigger_item.gamedata"
GUI_WINDOW_SIZE = "820x600"
DEFAULT_FONT = "Cascadia Code"
DEFAULT_FONT_SIZE = 10
DEFAULT_BUTTON_WIDTH = 10
MAX_LEN_NAME = 10
MIN_LEN_NAME = 0
